#!/usr/bin/env bash
set -euo pipefail

# trial-on-repo.sh — Run clarion trial on a user's repository
#
# Usage:
#   ./scripts/trial-on-repo.sh /path/to/repo [--bug-title "title"]

CLARION="${CLARION_BIN:-clarion}"
TRIAL_OUT_DIR=""
DOCTOR_CODE=0
SCAN_CODE=0
PR_CODE=0
REPORT_CODE=0
BUG_CODE=0

# --- Parse arguments ---
REPO_PATH=""
BUG_TITLE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bug-title)
      BUG_TITLE="$2"
      shift 2
      ;;
    -*)
      echo "Unknown option: $1" >&2
      exit 2
      ;;
    *)
      REPO_PATH="$1"
      shift
      ;;
  esac
done

# --- Validate ---
if [ -z "$REPO_PATH" ]; then
  echo "Usage: $0 /path/to/repo [--bug-title \"title\"]" >&2
  echo "" >&2
  echo "Runs clarion trial against the specified repository." >&2
  echo "Generates .clarion-trial/clarion_trial_report.md in the target repo." >&2
  exit 2
fi

if [ ! -d "$REPO_PATH" ]; then
  echo "Error: '$REPO_PATH' is not a directory" >&2
  exit 2
fi

if [ ! -d "$REPO_PATH/.git" ]; then
  echo "Error: '$REPO_PATH' is not a git repository (no .git directory)" >&2
  exit 2
fi

if ! "$CLARION" --version >/dev/null 2>&1; then
  echo "Error: clarion binary is not runnable: $CLARION" >&2
  exit 2
fi

TRIAL_OUT_DIR="$REPO_PATH/.clarion-trial"
mkdir -p "$TRIAL_OUT_DIR"

run_trial_step() {
  local name="$1"
  shift
  local log="$TRIAL_OUT_DIR/${name}.log"

  set +e
  "$@" 2>&1 | tee "$log"
  local code=${PIPESTATUS[0]}
  set -e

  return "$code"
}

echo "=== Clarion Trial ==="
echo "Target: $REPO_PATH"
echo ""

# --- Step 1: Doctor ---
echo "1. Running trial doctor..."
if run_trial_step "trial-doctor" "$CLARION" trial doctor --repo "$REPO_PATH"; then
  DOCTOR_CODE=0
  echo "   Done."
else
  DOCTOR_CODE=$?
  echo "   Trial doctor returned non-zero status ($DOCTOR_CODE). Continuing with collected output."
fi
echo ""

# --- Step 2: Scan ---
echo "2. Running trial scan..."
if run_trial_step "trial-scan" "$CLARION" trial scan --repo "$REPO_PATH"; then
  SCAN_CODE=0
  echo "   Done."
else
  SCAN_CODE=$?
  echo "   Trial scan returned non-zero status ($SCAN_CODE). Continuing with collected output."
fi
echo ""

# --- Step 3: PR ---
echo "3. Running trial pr..."
if run_trial_step "trial-pr" "$CLARION" trial pr --repo "$REPO_PATH"; then
  PR_CODE=0
  echo "   Done."
else
  PR_CODE=$?
  echo "   Trial pr returned non-zero status ($PR_CODE). Continuing with collected output."
fi
echo ""

# --- Step 4: Report ---
echo "4. Running trial report..."
if run_trial_step "trial-report" "$CLARION" trial report --repo "$REPO_PATH"; then
  REPORT_CODE=0
  echo "   Done."
else
  REPORT_CODE=$?
  echo "   Trial report returned non-zero status ($REPORT_CODE). A fallback bridge report will be written."
fi
echo ""

# --- Step 5: Bug (optional) ---
if [ -n "$BUG_TITLE" ]; then
  echo "5. Running trial bug..."
  if run_trial_step "trial-bug" "$CLARION" trial bug --repo "$REPO_PATH" --title "$BUG_TITLE"; then
    BUG_CODE=0
    echo "   Done."
  else
    BUG_CODE=$?
    echo "   Trial bug returned non-zero status ($BUG_CODE). Continuing with collected output."
  fi
  echo ""
fi

# --- Output ---
REPORT_PATH="$REPO_PATH/.clarion-trial/clarion_trial_report.md"

if [ ! -f "$REPORT_PATH" ]; then
  cat > "$REPORT_PATH" << EOF
# Clarion Trial Bridge Report

This fallback report was generated by \`scripts/trial-on-repo.sh\` because the
canonical \`clarion trial report\` output was unavailable for this run.

## Step Status

- trial doctor: exit code $DOCTOR_CODE
- trial scan: exit code $SCAN_CODE
- trial pr: exit code $PR_CODE
- trial report: exit code $REPORT_CODE
$(if [ -n "$BUG_TITLE" ]; then printf '%s\n' "- trial bug: exit code $BUG_CODE"; fi)

## Collected Logs

- \`.clarion-trial/trial-doctor.log\`
- \`.clarion-trial/trial-scan.log\`
- \`.clarion-trial/trial-pr.log\`
- \`.clarion-trial/trial-report.log\`
$(if [ -n "$BUG_TITLE" ]; then printf '%s\n' "- \`.clarion-trial/trial-bug.log\`"; fi)

## Recommended Next Step

Start by reading \`.clarion-trial/trial-scan.log\` to see which trial lanes are
available in this repository. If PR governance is available, make a small diff
and re-run the PR lane to get a more informative governance result.
EOF
fi

if [ -f "$REPORT_PATH" ]; then
  echo "=== Trial complete ==="
  echo "Report: $REPORT_PATH"
else
  echo "=== Trial complete ==="
  echo "Warning: Expected report not found at $REPORT_PATH"
  echo "Check the output above for errors."
fi
