#!/usr/bin/env bash
set -euo pipefail

# trial-on-repo.sh — Run clarion trial on a user's repository
#
# Usage:
#   ./scripts/trial-on-repo.sh /path/to/repo [--bug-title "title"]

CLARION="${CLARION_BIN:-clarion}"
TRIAL_OUT_DIR=""
DOCTOR_CODE=0
SCAN_CODE=0
PR_CODE=0
REPORT_CODE=0
BUG_CODE=0

# --- Parse arguments ---
REPO_PATH=""
BUG_TITLE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bug-title)
      BUG_TITLE="$2"
      shift 2
      ;;
    -*)
      echo "Unknown option: $1" >&2
      exit 2
      ;;
    *)
      REPO_PATH="$1"
      shift
      ;;
  esac
done

# --- Validate ---
if [ -z "$REPO_PATH" ]; then
  echo "Usage: $0 /path/to/repo [--bug-title \"title\"]" >&2
  echo "" >&2
  echo "Runs clarion trial against the specified repository." >&2
  echo "Writes a canonical Trial report when available, otherwise .clarion-trial/bridge_report.md." >&2
  exit 2
fi

if [ ! -d "$REPO_PATH" ]; then
  echo "Error: '$REPO_PATH' is not a directory" >&2
  exit 2
fi

if [ ! -d "$REPO_PATH/.git" ]; then
  echo "Error: '$REPO_PATH' is not a git repository (no .git directory)" >&2
  exit 2
fi

if ! "$CLARION" --version >/dev/null 2>&1; then
  echo "Error: clarion binary is not runnable: $CLARION" >&2
  exit 2
fi

TRIAL_OUT_DIR="$REPO_PATH/.clarion-trial"
mkdir -p "$TRIAL_OUT_DIR"
CANONICAL_REPORT_PATH="$TRIAL_OUT_DIR/clarion_trial_report.md"
BRIDGE_REPORT_PATH="$TRIAL_OUT_DIR/bridge_report.md"
rm -f "$CANONICAL_REPORT_PATH" "$BRIDGE_REPORT_PATH"

run_trial_step() {
  local name="$1"
  shift
  local log="$TRIAL_OUT_DIR/${name}.log"

  set +e
  "$@" 2>&1 | tee "$log"
  local code=${PIPESTATUS[0]}
  set -e

  return "$code"
}

echo "=== Clarion Trial ==="
echo "Target: $REPO_PATH"
echo ""

# --- Step 1: Doctor ---
echo "1. Running trial doctor..."
if run_trial_step "trial-doctor" "$CLARION" trial doctor --repo "$REPO_PATH"; then
  DOCTOR_CODE=0
  echo "   Done."
else
  DOCTOR_CODE=$?
  echo "   Trial doctor returned non-zero status ($DOCTOR_CODE). Continuing with collected output."
fi
echo ""

# --- Step 2: Scan ---
echo "2. Running trial scan..."
if run_trial_step "trial-scan" "$CLARION" trial scan --repo "$REPO_PATH"; then
  SCAN_CODE=0
  echo "   Done."
else
  SCAN_CODE=$?
  echo "   Trial scan returned non-zero status ($SCAN_CODE). Continuing with collected output."
fi
echo ""

# --- Step 3: PR ---
echo "3. Running trial pr..."
if run_trial_step "trial-pr" "$CLARION" trial pr --repo "$REPO_PATH"; then
  PR_CODE=0
  echo "   Done."
else
  PR_CODE=$?
  echo "   Trial pr returned non-zero status ($PR_CODE). Continuing with collected output."
fi
echo ""

# --- Step 4: Report ---
echo "4. Running trial report..."
if run_trial_step "trial-report" "$CLARION" trial report --repo "$REPO_PATH"; then
  REPORT_CODE=0
  echo "   Done."
else
  REPORT_CODE=$?
  echo "   Trial report returned non-zero status ($REPORT_CODE). A fallback bridge report will be written."
fi
echo ""

# --- Step 5: Bug (optional) ---
if [ -n "$BUG_TITLE" ]; then
  echo "5. Running trial bug..."
  if run_trial_step "trial-bug" "$CLARION" trial bug --repo "$REPO_PATH" --title "$BUG_TITLE"; then
    BUG_CODE=0
    echo "   Done."
  else
    BUG_CODE=$?
    echo "   Trial bug returned non-zero status ($BUG_CODE). Continuing with collected output."
  fi
  echo ""
fi

# --- Derive lane status labels ---
status_label() {
  local code="$1"
  if [ "$code" -eq 0 ]; then
    printf "pass"
  elif [ "$code" -eq 2 ]; then
    printf "unavailable"
  else
    printf "partial (exit %d)" "$code"
  fi
}

DOCTOR_STATUS=$(status_label "$DOCTOR_CODE")
SCAN_STATUS=$(status_label "$SCAN_CODE")
PR_STATUS=$(status_label "$PR_CODE")
REPORT_STATUS=$(status_label "$REPORT_CODE")

# --- Output ---
if [ ! -f "$CANONICAL_REPORT_PATH" ]; then
  cat > "$BRIDGE_REPORT_PATH" << EOF
# Clarion Trial Bridge Report

This is not a Clarion Trial report.

This fallback was generated by \`scripts/trial-on-repo.sh\` because the
canonical \`clarion trial report\` output was unavailable for this run.

## Lane Status

| Command | Status |
|---------|--------|
| trial doctor | $DOCTOR_STATUS |
| trial scan | $SCAN_STATUS |
| trial pr | $PR_STATUS |
| trial report | not produced |
$(if [ -n "$BUG_TITLE" ]; then printf '| trial bug | %s |\n' "$(status_label "$BUG_CODE")"; fi)

## What this means

The Clarion Trial command surface is reachable. The canonical report was not
produced in this environment. This may be because:
- The repository does not yet have enough governance surface for a full report
- The Clarion binary version does not support \`trial report\` for this repo
- A prerequisite lane (doctor or scan) returned partial results

## Collected Logs

- \`.clarion-trial/trial-doctor.log\`
- \`.clarion-trial/trial-scan.log\`
- \`.clarion-trial/trial-pr.log\`
- \`.clarion-trial/trial-report.log\`
$(if [ -n "$BUG_TITLE" ]; then printf '%s\n' "- \`.clarion-trial/trial-bug.log\`"; fi)

## Recommended Next Step

1. Read \`.clarion-trial/trial-scan.log\` to see which governance lanes are
   available in this repository.
2. If PR governance is available, make a small diff and re-run:
   \`\`\`bash
   ./scripts/trial-on-repo.sh /path/to/repo
   \`\`\`
3. Install the latest Clarion CLI and retry:
   \`\`\`bash
   clarion trial report --repo .
   \`\`\`
EOF
fi

if [ -f "$CANONICAL_REPORT_PATH" ]; then
  echo "=== Trial complete ==="
  echo "Canonical Trial report: $CANONICAL_REPORT_PATH"
elif [ -f "$BRIDGE_REPORT_PATH" ]; then
  echo "=== Trial complete ==="
  echo "Canonical Trial report was not produced."
  echo "Wrapper-owned bridge report: $BRIDGE_REPORT_PATH"
  echo "This is not a Clarion Trial report."
else
  echo "=== Trial complete ==="
  echo "Warning: Neither a canonical Trial report nor a bridge report was produced."
  echo "Check the output above for errors."
fi
